version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: FMS-DB
    restart: always
    environment:
      MYSQL_DATABASE: feedbackdb
      MYSQL_ROOT_PASSWORD: 2013@Mraoanshu
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./deployment/feedbackdb_schema.sql:/docker-entrypoint-initdb.d/feedbackdb_schema.sql:ro
      - ./deployment/feedbackdb_seed_users.sql:/docker-entrypoint-initdb.d/feedbackdb_seed_users.sql:ro
    networks:
      - ecommerce-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p2013@Mraoanshu"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: fms-backend
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/feedbackdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 2013@Mraoanshu
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - ecommerce-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: fms-frontend
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - backend
    networks:
      - ecommerce-net

volumes:
  db_data:

networks:
  ecommerce-net:
    driver: bridge
